### ISSUE TITLE
위키 항목 신규입력

### ISSUE THREAD

**Issue by neropsys** [f-lab-edu/awesome-wiki#11]
### 개요
위키에 새로운 항목을 추가해주는 기능

### AS-IS
위키에 저장될 항목에 대한 기본 데이터 형식이 존재하지 않는 상태
또한 신규 항목이 추가될 경우에 대한 예외상황을 정의하지 않은 상태

### TO-BE
위키의 기본이 될 항목 데이터의 형식을 정의.
등록 로직에 대한 기본적인 예외상황 처리 방안을 수립
추후 사용자가 해당 항목의 역사를 조회하거나 변경점을 조회할 수 있는 기능을 제공

**Comment by neropsys** [comment]
제목: 100자 미만
내용: 10000자 미만
![image](https://user-images.githubusercontent.com/4974667/116527552-c0dc4300-a915-11eb-9900-9b833c545c58.png)
이런 식으로 테이블의 구조를 생각해두었습니다. 혹시 제가 생각치 못한 부분이나 구조적으로 문제가 있을지 확인 부탁드립니다.
@kmmin78 @f-lab-hwan

**Comment by FrancescoJo** [comment]
> 제목: 100자 미만
> 내용: 10000자 미만
> ![image](https://user-images.githubusercontent.com/4974667/116527552-c0dc4300-a915-11eb-9900-9b833c545c58.png)
> 이런 식으로 테이블의 구조를 생각해두었습니다. 혹시 제가 생각치 못한 부분이나 구조적으로 문제가 있을지 확인 부탁드립니다.
> @kmmin78 @f-lab-hwan

일단은 '테이블' 보다는 도메인 모델만 먼저 생각해 보시죠. '테이블' 같은 구체적인 정보는 가급적 최대한 늦게 결정하시는 게 좋습니다.

왜냐면 현업에서는 요구사항이 갑자기 바뀌어서 RDBMS 를 쓰지 말라고 하거나, Cassandra 같은 NoSQL 을 쓰라는 요구사항이 올 수도 있거든요.

구상하신 '테이블' 을 `interface` 키워드만으로 한번 구상해 보시죠.

**Comment by FrancescoJo** [comment]
우측에 레이블 붙여주시고 TO-BE 항목에 이 작업으로 **누가 어떤 이득을 얻는지**를 명시해주세요~
