### ISSUE TITLE
코드리뷰 피드백 반영

### ISSUE THREAD

**Issue by kmmin78** [f-lab-edu/awesome-wiki#15]
개요
코드리뷰 피드백 반영하여 코드 품질 향상

AS-IS
수정 전 코드로 code smell이 많이 나는 상태.

TO-BE
피드백 반영해서 코드 품질 향상.
앞으로 코드 작성할 때 참고하여 더 좋은 코드를 생산하기 위함.

**Comment by FrancescoJo** [comment]
관련 Pull request 가 완료 상태이므로 이슈 종결 처리
