### ISSUE TITLE
공통 코드 포맷 지정

### ISSUE THREAD

**Issue by f-lab-hwan** [f-lab-edu/awesome-wiki#7]
### 개요
공통 코드 포맷 및 detekt 규칙을 프로젝트 root 에 추가한다.

### AS-IS
모두들 사용할 수 있는 코드 포맷과 detekt 규칙이 없음.

### TO-BE
공통 코드포맷을 지정해 모든 참여자들이 코드 리뷰 시간에 스타일보다는 그 내용에 좀 더 집중할 수 있도록 돕는다.

**Comment by neropsys** [comment]
#17 올려주신 코드스타일 xml로 코드 포맷을 적용 후 detekt를 실행시키면 모든 파일의 끝에 newLine이 없어 NewLineAtEndOfFile 경고가 발생합니다. detekt에서 해당 경고를 체크하지 않도록 수정하거나 코드스타일 xml에서 모든 파일 끝에 newLine이 붙도록 수정해야합니다.

**Comment by FrancescoJo** [comment]
> #17 올려주신 코드스타일 xml로 코드 포맷을 적용 후 detekt를 실행시키면 모든 파일의 끝에 newLine이 없어 NewLineAtEndOfFile 경고가 발생합니다. detekt에서 해당 경고를 체크하지 않도록 수정하거나 코드스타일 xml에서 모든 파일 끝에 newLine이 붙도록 수정해야합니다.

네. 파일 끝에 newLine 을 추가하는 이유는 Unix 환경의 경우 모든 텍스트 파일의 끝에는 newLine 이 존재해야 해서 그렇습니다.

https://thoughtbot.com/blog/no-newline-at-end-of-file

그래서 경고 읽어보셨다면 모든 파일 끝에 newLine 을 붙이는 코드 스타일을 만들어서 PR 올려주시기 바랍니다.

CC: @kmmin78
